// ═══════════════════════════════════════════════════════════
// SRI MATANGI ASHTOTTARA SHATANAMAVALI
// 108 Names of Śrī Mātaṅgī
// Source: manblunder.com — Krishna Vallapareddy
// ═══════════════════════════════════════════════════════════

export interface Name108 {
  number: number;
  iast: string;
  devanagari: string;
  meaning: string;
  category?: string;
}

export const introductionText = `The aṣṭottara śatanāmāvali (108 names) of Śrī Mātaṅgī is a treatise in itself, containing the very essence of the Śrī Mātaṅgī Sahasranāma. All the benefits that can be accrued through reciting the sahasranāma may also accrue through the aṣṭottara śatanāmāvali, if we meditate upon the meanings of each nāma.

The aṣṭottara śatanāmāvali describes the key attributes of Śrī Mātaṅgī, spanning across the entire spectrum ranging from Her physical attributes to Her spiritual splendor — from purāṇic accounts, tantric śāstras, relationship with Śrī Vidyā, Kuṇḍalinī meditation, and Her aspect as Brahman Itself.

She is the tantric form of Sarasvatī (Vāṇī), the Goddess of Knowledge. From the nāmas, we see Her true form and splendor. Worshipping Her in majestic form and beauty provides not only knowledge of what we seek, but also the greatest spiritual secrets and the real knowledge of our own true form — that of pure consciousness Itself.

In a Śrī Vidyā parlance, She is Śyāmalā, the Chief Advisor of Śrī Lalitā. She and Śrī Vārāhi are the closest to Śrī Lalitā and lead us to Her. In the human body, Śrī Mātaṅgī is the left nāḍī — Iḍā — corresponding to the left nostril and the right hemisphere of the brain, indicating artistic, logical, and creative aspects. When the nāḍīs are balanced, the Kuṇḍalinī rises through the Suṣumṇā, energizing the cakras and ultimately revealing our true existence as self-realization.`;

export const names108: Name108[] = [
  {
    number: 1,
    iast: "oṃ śrī-mahāmatta-mātaṅginyai namaḥ",
    devanagari: "ॐ श्रीमहामत्तमातङ्गिन्यै नमः",
    meaning: "Salutations to the One who is overjoyed and intoxicated with divine knowledge of the arts and sciences. She is the source and cause of all knowledge — verbal and written, music, science. She is also the power of an elephant, associated with Ucchiṣṭa Gaṇapati.",
    category: "Essence",
  },
  {
    number: 2,
    iast: "oṃ śrī-siddhi-rūpāyai namaḥ",
    devanagari: "ॐ श्रीसिद्धिरूपायै नमः",
    meaning: "Salutations to the One who is the cause of all accomplishment and fulfillment. Her grace can provide complete success in all endeavors.",
    category: "Power",
  },
  {
    number: 3,
    iast: "oṃ śrī-yoginyai namaḥ",
    devanagari: "ॐ श्रीयोगिन्यै नमः",
    meaning: "Salutations to the One who is joined with Her consort — a representation of the Śiva-Śaktī-aikya, the union of individual consciousness with the dynamic and static superconsciousness.",
    category: "Union",
  },
  {
    number: 4,
    iast: "oṃ śrī-bhadra-kālyai namaḥ",
    devanagari: "ॐ श्रीभद्रकाल्यै नमः",
    meaning: "Salutations to the One who is the firestorm of knowledge that destroys all ignorance. Bhadrakālī is the great knowledge that comes from the opening of the third-eye Ājñā cakra.",
    category: "Wisdom",
  },
  {
    number: 5,
    iast: "oṃ śrī-ramāyai namaḥ",
    devanagari: "ॐ श्रीरमायै नमः",
    meaning: "Salutations to the One who is most delightful, loving and pleasing. She is the giver of all wealth. She is Lakṣmī.",
    category: "Abundance",
  },
  {
    number: 6,
    iast: "oṃ śrī-bhavānyai namaḥ",
    devanagari: "ॐ श्रीभवान्यै नमः",
    meaning: "Salutations to the One who is Śaktī — the Supreme bliss who has emerged from Śiva as His independent power — the dynamic superconsciousness representing the Whole of existence.",
    category: "Essence",
  },
  {
    number: 7,
    iast: "oṃ śrī-bhava-prītidāyai namaḥ",
    devanagari: "ॐ श्रीभवप्रीतिदायै नमः",
    meaning: "Salutations to the One who is fond of Creation and always in a state of joyful excitement.",
    category: "Joy",
  },
  {
    number: 8,
    iast: "oṃ śrī-bhūti-yuktāyai namaḥ",
    devanagari: "ॐ श्रीभूतियुक्तायै नमः",
    meaning: "Salutations to the One who represents and is in all five basic natural elements — water, air, earth, fire, and space.",
    category: "Nature",
  },
  {
    number: 9,
    iast: "oṃ śrī-bhava-ārādhitāyai namaḥ",
    devanagari: "ॐ श्रीभवाराधितायै नमः",
    meaning: "Salutations to the One who worships and is with Śiva. She is Śaktī Herself.",
    category: "Union",
  },
  {
    number: 10,
    iast: "oṃ śrī-bhūti-sampatti-karyai namaḥ",
    devanagari: "ॐ श्रीभूतिसम्पत्तिकर्यै नमः",
    meaning: "Salutations to the One who enriches all five natural elements with Her presence.",
    category: "Nature",
  },
  {
    number: 11,
    iast: "oṃ śrī-jana-ādhīśa-mātre namaḥ",
    devanagari: "ॐ श्रीजनाधीशमात्रे नमः",
    meaning: "Salutations to the Divine Mother who rules over all living entities.",
    category: "Sovereignty",
  },
  {
    number: 12,
    iast: "oṃ śrī-dhanāgāra-dṛṣṭyai namaḥ",
    devanagari: "ॐ श्रीधनागारदृष्ट्यै नमः",
    meaning: "Salutations to the One who dwells and watches over all wealth — material and spiritual.",
    category: "Abundance",
  },
  {
    number: 13,
    iast: "oṃ śrī-dhaneśa-arcitāyai namaḥ",
    devanagari: "ॐ श्रीधनेशार्चितायै नमः",
    meaning: "Salutations to the One who is worshipped to obtain immense wealth — material and spiritual.",
    category: "Abundance",
  },
  {
    number: 14,
    iast: "oṃ śrī-dhīravāpyai namaḥ",
    devanagari: "ॐ श्रीधीरवाप्यै नमः",
    meaning: "Salutations to the One who resides in all water bodies. She is intelligence present in all waters guiding them to the great oceans, representing abundance and resources.",
    category: "Nature",
  },
  {
    number: 15,
    iast: "oṃ śrī-varāṅgyai namaḥ",
    devanagari: "ॐ श्रीवराङ्ग्यै नमः",
    meaning: "Salutations to the One who is very beautiful, well-shaped and extremely intelligent — the source of all beauty and knowledge.",
    category: "Beauty",
  },
  {
    number: 16,
    iast: "oṃ śrī-prakṛṣṭāyai namaḥ",
    devanagari: "ॐ श्रीप्रकृष्टायै नमः",
    meaning: "Salutations to the One who is very eminent and spread across all realms of space and time.",
    category: "Omnipresence",
  },
  {
    number: 17,
    iast: "oṃ śrī-prabhā-rūpiṇyai namaḥ",
    devanagari: "ॐ श्रीप्रभारूपिण्यै नमः",
    meaning: "Salutations to the One who is brilliantly radiant and splendorous in appearance.",
    category: "Light",
  },
  {
    number: 18,
    iast: "oṃ śrī-kāma-rūpāyai namaḥ",
    devanagari: "ॐ श्रीकामरूपायै नमः",
    meaning: "Salutations to the One who is the object of desire and accomplishment — and who can take any form as per Her wish.",
    category: "Power",
  },
  {
    number: 19,
    iast: "oṃ śrī-prahṛṣṭāyai namaḥ",
    devanagari: "ॐ श्रीप्रहृष्टायै नमः",
    meaning: "Salutations to the One in an extremely delightful state and ready to accept all prayers.",
    category: "Joy",
  },
  {
    number: 20,
    iast: "oṃ śrī-mahā-kīrtidāyai namaḥ",
    devanagari: "ॐ श्रीमहाकीर्तिदायै नमः",
    meaning: "Salutations to the One who is most honorable and has acquired immense fame through Her grace on devotees.",
    category: "Glory",
  },
  {
    number: 21,
    iast: "oṃ śrī-karṇanālyai namaḥ",
    devanagari: "ॐ श्रीकर्णनाल्यै नमः",
    meaning: "Salutations to the One with very beautiful lotus-petal-shaped ears. She hears and addresses all concerns of Her sincere devotees.",
    category: "Listening",
  },
  {
    number: 22,
    iast: "oṃ śrī-karālyai namaḥ",
    devanagari: "ॐ श्रीकराल्यै नमः",
    meaning: "Salutations to the One who is none other than Kālī — the aspect of Śaktī who severs ego and provides true knowledge. She quickly removes ignorance and aligns us with our true self.",
    category: "Transformation",
  },
  {
    number: 23,
    iast: "oṃ śrī-bhagā-ghora-rūpāyai namaḥ",
    devanagari: "ॐ श्रीभगाघोररूपायै नमः",
    meaning: "Salutations to the One who is majestic, graceful, venerable and also terrific in appearance — the dispenser of everything that there is.",
    category: "Sovereignty",
  },
  {
    number: 24,
    iast: "oṃ śrī-bhaga-aṅgyai namaḥ",
    devanagari: "ॐ श्रीभगाङ्ग्यै नमः",
    meaning: "Salutations to the One who bestows all types of knowledge, arts, wealth and grace upon sincere devotees.",
    category: "Wisdom",
  },
  {
    number: 25,
    iast: "oṃ śrī-bhagā-vāhyai namaḥ",
    devanagari: "ॐ श्रीभगावाह्यै नमः",
    meaning: "Salutations to the One who is the vehicle of delivery of all knowledge, arts, wealth and prosperity to sincere devotees.",
    category: "Grace",
  },
  {
    number: 26,
    iast: "oṃ śrī-bhaga-prīti-dāyai namaḥ",
    devanagari: "ॐ श्रीभगप्रीतिदायै नमः",
    meaning: "Salutations to the One who is joyful, loving and affectionate to sincere devotees, taking care of all their welfare.",
    category: "Love",
  },
  {
    number: 27,
    iast: "oṃ śrī-bhīma-rūpāyai namaḥ",
    devanagari: "ॐ श्रीभीमरूपायै नमः",
    meaning: "Salutations to the One who has a formidable appearance yet remains very amiable to Her devotees.",
    category: "Power",
  },
  {
    number: 28,
    iast: "oṃ śrī-bhavānī-mahā-kauśikyai namaḥ",
    devanagari: "ॐ श्रीभवानीमहाकौशिक्यै नमः",
    meaning: "Salutations to the One who grants supreme blissful state and is the compendium of all knowledge leading to liberation.",
    category: "Liberation",
  },
  {
    number: 29,
    iast: "oṃ śrī-kośa-pūrṇāyai namaḥ",
    devanagari: "ॐ श्रीकोशपूर्णायै नमः",
    meaning: "Salutations to the One who is the Supreme knowledge — Mahāvidyā. She represents all knowledge that exists.",
    category: "Wisdom",
  },
  {
    number: 30,
    iast: "oṃ śrī-kiśoryai namaḥ",
    devanagari: "ॐ श्रीकिशोर्यै नमः",
    meaning: "Salutations to the One who is all-enticing and eternally youthful — always in a blissful state depicted as full of youth and vigor.",
    category: "Joy",
  },
  {
    number: 31,
    iast: "oṃ śrī-kiśora-priya-ānanda-īhāyai namaḥ",
    devanagari: "ॐ श्रीकिशोरप्रियानन्दईहायै नमः",
    meaning: "Salutations to the One who is eternally youthful in appearance, blissful and extremely desirable.",
    category: "Joy",
  },
  {
    number: 32,
    iast: "oṃ śrī-mahā-kāraṇāyai namaḥ",
    devanagari: "ॐ श्रीमहाकारणायै नमः",
    meaning: "Salutations to the One who is the cause of all Creation, Sustenance, destruction, dissolution and re-creation.",
    category: "Essence",
  },
  {
    number: 33,
    iast: "oṃ śrī-kāraṇāyai namaḥ",
    devanagari: "ॐ श्रीकारणायै नमः",
    meaning: "Salutations to the One who is the cause of everything. All that happens is as per Her desire — She is the power behind karmic actions.",
    category: "Essence",
  },
  {
    number: 34,
    iast: "oṃ śrī-karma-śīlāyai namaḥ",
    devanagari: "ॐ श्रीकर्मशीलायै नमः",
    meaning: "Salutations to the One who is the force behind karmic results — the One who steadfastly imposes karmic laws on all.",
    category: "Karma",
  },
  {
    number: 35,
    iast: "oṃ śrī-kapālyai namaḥ",
    devanagari: "ॐ श्रीकपाल्यै नमः",
    meaning: "Salutations to the One who slashes ego and grants self-realization. The skull represents an 'empty head' — one without ego. Only when we lose ourselves in Her can She be attained.",
    category: "Liberation",
  },
  {
    number: 36,
    iast: "oṃ śrī-prasiddhāyai namaḥ",
    devanagari: "ॐ श्रीप्रसिद्धायै नमः",
    meaning: "Salutations to the One who is universally known for Her greatness and power.",
    category: "Glory",
  },
  {
    number: 37,
    iast: "oṃ śrī-mahā-siddha-khaṇḍāyai namaḥ",
    devanagari: "ॐ श्रीमहासिद्धखण्डायै नमः",
    meaning: "Salutations to the One who is a part of all supernatural powers in existence and grants those powers to sincere devotees.",
    category: "Power",
  },
  {
    number: 38,
    iast: "oṃ śrī-makāra-priyāyai namaḥ",
    devanagari: "ॐ श्रीमकारप्रियायै नमः",
    meaning: "Salutations to the One who is fond of the five essentials of the left-hand tantric path — the Pañca-ma-kāras. In their highest spiritual interpretation: wine (amṛta of deep meditation), meat (control of speech/mantras), fish (the Iḍā and Piṅgalā nāḍīs), mudrā (spiritual association/satsang), and maithuna (Śiva-Śaktī union).",
    category: "Tantra",
  },
  {
    number: 39,
    iast: "oṃ śrī-māna-rūpāyai namaḥ",
    devanagari: "ॐ श्रीमानरूपायै नमः",
    meaning: "Salutations to the One who is the very creation itself. Everything that exists is Her. She is omniscient.",
    category: "Omnipresence",
  },
  {
    number: 40,
    iast: "oṃ śrī-maheśyai namaḥ",
    devanagari: "ॐ श्रीमहेश्यै नमः",
    meaning: "Salutations to the One who is both Śiva — the static superconsciousness — and Śaktī — the dynamic superconsciousness.",
    category: "Union",
  },
  {
    number: 41,
    iast: "oṃ śrī-mahollāsinyai namaḥ",
    devanagari: "ॐ श्रीमहोल्लासिन्यै नमः",
    meaning: "Salutations to the One who is playful and enacts the virtual illusion of Māyā. She is Lalitā — the playful.",
    category: "Joy",
  },
  {
    number: 42,
    iast: "oṃ śrī-lāsya-līlā-layāṅgyai namaḥ",
    devanagari: "ॐ श्रीलास्यलीलालयाङ्ग्यै नमः",
    meaning: "Salutations to the One who plays the cosmic dance at dissolution — referring to both cosmic dissolution and the absorption of individual consciousness into universal consciousness.",
    category: "Cosmic",
  },
  {
    number: 43,
    iast: "oṃ śrī-kṣamāyai namaḥ",
    devanagari: "ॐ श्रीक्षमायै नमः",
    meaning: "Salutations to the One who forgives all sins of sincere devotees and cleanses their karmas.",
    category: "Grace",
  },
  {
    number: 44,
    iast: "oṃ śrī-kṣema-śīlāyai namaḥ",
    devanagari: "ॐ श्रीक्षेमशीलायै नमः",
    meaning: "Salutations to the One who ensures and takes care of our wellbeing at all times.",
    category: "Protection",
  },
  {
    number: 45,
    iast: "oṃ śrī-kṣapā-kāriṇyai namaḥ",
    devanagari: "ॐ श्रीक्षपाकारिण्यै नमः",
    meaning: "Salutations to the One who is Space and Time itself — ensuring the smooth functioning of all creation.",
    category: "Cosmic",
  },
  {
    number: 46,
    iast: "oṃ śrī-akṣaya-prītidā-bhūti-yuktā-bhavānyai namaḥ",
    devanagari: "ॐ श्रीअक्षयप्रीतिदाभूतियुक्ताभवान्यै नमः",
    meaning: "Salutations to the One who is imperishable and ensures the sustenance of all five natural elements, granting pure joy and bliss to sincere devotees.",
    category: "Abundance",
  },
  {
    number: 47,
    iast: "oṃ śrī-bhava-ārādhitā-bhūti-satyātmikāyai namaḥ",
    devanagari: "ॐ श्रीभवाराधिताभूतिसत्यात्मिकायै नमः",
    meaning: "Salutations to the One who is always in reverence of Śiva and is the ultimate Truth in all existence.",
    category: "Essence",
  },
  {
    number: 48,
    iast: "oṃ śrī-prabha-udbhāsitāyai namaḥ",
    devanagari: "ॐ श्रीप्रभोद्भासितायै नमः",
    meaning: "Salutations to the One who shines forth like a billion suns.",
    category: "Light",
  },
  {
    number: 49,
    iast: "oṃ śrī-bhānu-bhāsvatkarāyai namaḥ",
    devanagari: "ॐ श्रीभानुभास्वत्करायै नमः",
    meaning: "Salutations to the One whose luminance is like that of the Sun — who lights up our lives and saves us from the abyss of ignorance.",
    category: "Light",
  },
  {
    number: 50,
    iast: "oṃ śrī-calat-kuṇḍalāyai namaḥ",
    devanagari: "ॐ श्रीचलत्कुण्डलायै नमः",
    meaning: "Salutations to the One with dazzling conch-shell earrings that stir the consciousness of meditating devotees.",
    category: "Beauty",
  },
  {
    number: 51,
    iast: "oṃ śrī-kāminī-kānta-yuktāyai namaḥ",
    devanagari: "ॐ श्रीकामिनीकान्तयुक्तायै नमः",
    meaning: "Salutations to the One who is the most loving and amicable aspect of the Divine Mother Śaktī.",
    category: "Love",
  },
  {
    number: 52,
    iast: "oṃ śrī-kapālā-acalāyai namaḥ",
    devanagari: "ॐ श्रीकपालाऽचलायै नमः",
    meaning: "Salutations to the One who grants devotees the ability to concentrate without distraction and meditate upon Her.",
    category: "Meditation",
  },
  {
    number: 53,
    iast: "oṃ śrī-kālaka-uddhāriṇyai namaḥ",
    devanagari: "ॐ श्रीकालकोद्धारिण्यै नमः",
    meaning: "Salutations to the One who appears elevated amongst multitudes of clouds — a reference to Her presence in the Sahasrāra cakra.",
    category: "Kundalini",
  },
  {
    number: 54,
    iast: "oṃ śrī-kadamba-priyāyai namaḥ",
    devanagari: "ॐ श्रीकदम्बप्रियायै नमः",
    meaning: "Salutations to the One who is very fond of fragrant kadamba blossoms — referencing the petals of all cakras in the body and their energization.",
    category: "Kundalini",
  },
  {
    number: 55,
    iast: "oṃ śrī-koṭaryai namaḥ",
    devanagari: "ॐ श्रीकोटर्यै नमः",
    meaning: "Salutations to the One who is infinite and depicted with minimal coverings.",
    category: "Essence",
  },
  {
    number: 56,
    iast: "oṃ śrī-koṭa-dehāyai namaḥ",
    devanagari: "ॐ श्रीकोटदेहायै नमः",
    meaning: "Salutations to the One whose form is infinite — omniscient and omnipresent, not a finite being.",
    category: "Omnipresence",
  },
  {
    number: 57,
    iast: "oṃ śrī-kramāyai namaḥ",
    devanagari: "ॐ श्रीक्रमायै नमः",
    meaning: "Salutations to the One who can be realized following a regular prescribed method. Her nature becomes transparent gradually — progressively, not all at once.",
    category: "Realization",
  },
  {
    number: 58,
    iast: "oṃ śrī-kīrtidāyai namaḥ",
    devanagari: "ॐ श्रीकीर्तिदायै नमः",
    meaning: "Salutations to the One who is known all over the universe and grants instant fame and glory to devotees.",
    category: "Glory",
  },
  {
    number: 59,
    iast: "oṃ śrī-karṇa-rūpāyai namaḥ",
    devanagari: "ॐ श्रीकर्णरूपायै नमः",
    meaning: "Salutations to the One who is in the form of ears — all knowledge we seek, hear and gain is through Her grace.",
    category: "Listening",
  },
  {
    number: 60,
    iast: "oṃ śrī-kākṣmyai namaḥ",
    devanagari: "ॐ श्रीकाक्ष्म्यै नमः",
    meaning: "Salutations to the One whose side glance alone is enough to grant self-realization and lead to liberation.",
    category: "Liberation",
  },
  {
    number: 61,
    iast: "oṃ śrī-kṣamāṅyai namaḥ",
    devanagari: "ॐ श्रीक्षमाङ्यै नमः",
    meaning: "Salutations to the One who has infinite patience and forbearance.",
    category: "Grace",
  },
  {
    number: 62,
    iast: "oṃ śrī-kṣaya-prema-rūpāyai namaḥ",
    devanagari: "ॐ श्रीक्षयप्रेमरूपायै नमः",
    meaning: "Salutations to the One who is the abode and representation of infinite, true love.",
    category: "Love",
  },
  {
    number: 63,
    iast: "oṃ śrī-kṣapāyai namaḥ",
    devanagari: "ॐ श्रीक्षपायै नमः",
    meaning: "Salutations to the One who is timeless — whose presence can be felt at all times by devotees.",
    category: "Essence",
  },
  {
    number: 64,
    iast: "oṃ śrī-kṣayākṣāyai namaḥ",
    devanagari: "ॐ श्रीक्षयाक्षायै नमः",
    meaning: "Salutations to the One who is Consciousness Itself and dwells everywhere — the cause and source of all Knowledge that exists and shall exist.",
    category: "Consciousness",
  },
  {
    number: 65,
    iast: "oṃ śrī-kṣaya-āhvāyai namaḥ",
    devanagari: "ॐ श्रीक्षयाह्वायै नमः",
    meaning: "Salutations to the One who is the backbone of all existence — Creator, Preserver and Destroyer — the dwelling and the dweller.",
    category: "Essence",
  },
  {
    number: 66,
    iast: "oṃ śrī-kṣaya-prāntarāyai namaḥ",
    devanagari: "ॐ श्रीक्षयप्रान्तरायै नमः",
    meaning: "Salutations to the One who is also the Path that leads to Her — self-realization and liberation.",
    category: "Liberation",
  },
  {
    number: 67,
    iast: "oṃ śrī-kṣavat-kāminyai namaḥ",
    devanagari: "ॐ श्रीक्षवत्कामिन्यै नमः",
    meaning: "Salutations to the dark-complexioned, affectionate and most lovely aspect of the Divine Mother.",
    category: "Beauty",
  },
  {
    number: 68,
    iast: "oṃ śrī-kṣāriṇyai namaḥ",
    devanagari: "ॐ श्रीक्षारिण्यै नमः",
    meaning: "Salutations to the One who is like a flowing river of compassion and an ocean of consciousness.",
    category: "Love",
  },
  {
    number: 69,
    iast: "oṃ śrī-kṣīra-pūrṇāyai namaḥ",
    devanagari: "ॐ श्रीक्षीरपूर्णायै नमः",
    meaning: "Salutations to the One who rules over the forces of karma, ensuring that every action begets its appropriate reaction.",
    category: "Karma",
  },
  {
    number: 70,
    iast: "oṃ śrī-śiva-aṅgyai namaḥ",
    devanagari: "ॐ श्रीशिवाङ्ग्यै नमः",
    meaning: "Salutations to the One who is part of Śiva — the dynamic Superconsciousness (Śaktī) that is part of the static Superconsciousness (Śiva).",
    category: "Union",
  },
  {
    number: 71,
    iast: "oṃ śrī-śākambharyai namaḥ",
    devanagari: "ॐ श्रीशाकम्भर्यै नमः",
    meaning: "Salutations to the One who nourishes all herbs and vegetables — the food-giver who provides nourishment to all beings.",
    category: "Nature",
  },
  {
    number: 72,
    iast: "oṃ śrī-śāka-dehāyai namaḥ",
    devanagari: "ॐ श्रीशाकदेहायै नमः",
    meaning: "Salutations to the One who is present in the nourishment itself — in everything that exists and in the empty void.",
    category: "Omnipresence",
  },
  {
    number: 73,
    iast: "oṃ śrī-mahā-śāka-yajñāyai namaḥ",
    devanagari: "ॐ श्रीमहाशाकयज्ञायै नमः",
    meaning: "Salutations to the One who is both the ingredient and the fire of all sacred sacrifices — both subject and object.",
    category: "Ritual",
  },
  {
    number: 74,
    iast: "oṃ śrī-phala-prāśakāyai namaḥ",
    devanagari: "ॐ श्रीफलप्राशकायै नमः",
    meaning: "Salutations to the One who is the result of all our actions — present in both fruitful and adverse results.",
    category: "Karma",
  },
  {
    number: 75,
    iast: "oṃ śrī-śaka-āhvā-āśaka-ākhyā-śakāyai namaḥ",
    devanagari: "ॐ श्रीशकाह्वाशकाख्याशकायै नमः",
    meaning: "Salutations to the One who ensures that the waste of one being becomes food for another — maintaining the food chain of the Universe.",
    category: "Nature",
  },
  {
    number: 76,
    iast: "oṃ śrī-śaka-ākṣa-antarā-uṣāyai namaḥ",
    devanagari: "ॐ श्रीशकाक्षान्तरोषायै नमः",
    meaning: "Salutations to the One who is the cerebrospinal fluid derived from the pineal gland — hidden as the third eye and revealed through intense meditation.",
    category: "Kundalini",
  },
  {
    number: 77,
    iast: "oṃ śrī-suroṣāyai namaḥ",
    devanagari: "ॐ श्रीसुरोषायै नमः",
    meaning: "Salutations to the One who is the luminance of the celestial beings.",
    category: "Light",
  },
  {
    number: 78,
    iast: "oṃ śrī-surekhāyai namaḥ",
    devanagari: "ॐ श्रीसुरेखायै नमः",
    meaning: "Salutations to the One who has beautiful lines all over Her form — Creator of all beauty and bounty abundant in the Universe.",
    category: "Beauty",
  },
  {
    number: 79,
    iast: "oṃ śrī-mahā-śeṣa-yajñopavīta-priyāyai namaḥ",
    devanagari: "ॐ श्रीमहाशेषयज्ञोपवीतप्रियायै नमः",
    meaning: "Salutations to the One who is the cakra-laden Suṣumnā (spinal cord) resembling a fine thread — cause of the thousand-petalled lotus blooming at the Sahasrāra cakra.",
    category: "Kundalini",
  },
  {
    number: 80,
    iast: "oṃ śrī-jayantī-jayā-jāgratī-yogya-rūpāyai namaḥ",
    devanagari: "ॐ श्रीजयन्तीजयाजाग्रतीयोग्यरूपायै नमः",
    meaning: "Salutations to the One who always grants victory and fulfilment — ever alert to the desires of Her devotees.",
    category: "Victory",
  },
  {
    number: 81,
    iast: "oṃ śrī-jaya-aṅgāyai namaḥ",
    devanagari: "ॐ श्रीजयाङ्गायै नमः",
    meaning: "Salutations to the One who is always present and guides devotees at all stages to ensure their victory.",
    category: "Victory",
  },
  {
    number: 82,
    iast: "oṃ śrī-japa-dhyāna-santuṣṭa-saṁjñāyai namaḥ",
    devanagari: "ॐ श्रीजपध्यानसन्तुष्टसंज्ञायै नमः",
    meaning: "Salutations to the One who is satisfied with mantra japa and meditation on Her form, granting the faculties of discernment and higher perception of reality.",
    category: "Meditation",
  },
  {
    number: 83,
    iast: "oṃ śrī-jaya-prāṇa-rūpāyai namaḥ",
    devanagari: "ॐ श्रीजयप्राणरूपायै नमः",
    meaning: "Salutations to the One who grants victory in every breath we take.",
    category: "Victory",
  },
  {
    number: 84,
    iast: "oṃ śrī-jaya-svarṇa-dehāyai namaḥ",
    devanagari: "ॐ श्रीजयस्वर्णदेहायै नमः",
    meaning: "Salutations to the One who is ever victorious and golden in appearance — a reference also to Her aspect as Bagalamukhi.",
    category: "Victory",
  },
  {
    number: 85,
    iast: "oṃ śrī-jaya-jvālinyai namaḥ",
    devanagari: "ॐ श्रीजयज्वालिन्यै नमः",
    meaning: "Salutations to the One who douses ego and grants the victory of self-realization. She also appears as Pratyaṅgirā, the Luminous One.",
    category: "Liberation",
  },
  {
    number: 86,
    iast: "oṃ śrī-yāminyai namaḥ",
    devanagari: "ॐ श्रीयामिन्यै नमः",
    meaning: "Salutations to the One who is the very journey and purpose of life itself.",
    category: "Essence",
  },
  {
    number: 87,
    iast: "oṃ śrī-yāmya-rūpāyai namaḥ",
    devanagari: "ॐ श्रीयाम्यरूपायै नमः",
    meaning: "Salutations to the One who is the great dark Void — and also none other than Śiva.",
    category: "Cosmic",
  },
  {
    number: 88,
    iast: "oṃ śrī-jagan-mātṛ-rūpāyai namaḥ",
    devanagari: "ॐ श्रीजगन्मातृरूपायै नमः",
    meaning: "Salutations to the One who is Śaktī — the Universal Divine Mother — the Supreme Bliss who emerged from Śiva as His independent power.",
    category: "Mother",
  },
  {
    number: 89,
    iast: "oṃ śrī-jagad-rakṣaṇāyai namaḥ",
    devanagari: "ॐ श्रीजगद्रक्षणायै नमः",
    meaning: "Salutations to the Universal Divine Mother who protects and sustains all realms and beings.",
    category: "Protection",
  },
  {
    number: 90,
    iast: "oṃ śrī-svadhā-vauṣaḍ-antāyai namaḥ",
    devanagari: "ॐ श्रीस्वधावौषडन्तायै नमः",
    meaning: "Salutations to the One who is Śaktī — the independent power of Śiva with no beginning or end — the enlightened Superconsciousness.",
    category: "Essence",
  },
  {
    number: 91,
    iast: "oṃ śrī-vilambā-vilambāyai namaḥ",
    devanagari: "ॐ श्रीविलम्बाविलम्बायै नमः",
    meaning: "Salutations to the One who is ever-reaching to Her devotees in need — Her grace is low-hanging, easily obtained for sincere devotees.",
    category: "Grace",
  },
  {
    number: 92,
    iast: "oṃ śrī-ṣaḍaṅgāyai namaḥ",
    devanagari: "ॐ श्रीषडङ्गायै नमः",
    meaning: "Salutations to the One with four arms and two legs — carrying noose (freeing from karmas), sword (slashing ego), goad and club (dispelling fears), and sometimes holding a Vīṇā. The four arms also represent the four Vedas.",
    category: "Form",
  },
  {
    number: 93,
    iast: "oṃ śrī-mahā-lamba-rūpā'si-hastā''pdā-hāriṇyai namaḥ",
    devanagari: "ॐ श्रीमहालम्बरूपाऽसिहस्ताऽऽप्दाहारिण्यै नमः",
    meaning: "Salutations to the One who is most magnanimous and extremely quick — like a deer — in reaching out to devotees and rescuing them in great danger.",
    category: "Protection",
  },
  {
    number: 94,
    iast: "oṃ śrī-mahā-maṅgalāyai namaḥ",
    devanagari: "ॐ श्रीमहामङ्गलायै नमः",
    meaning: "Salutations to the One who heralds auspiciousness all around devotees and grants every wish.",
    category: "Auspiciousness",
  },
  {
    number: 95,
    iast: "oṃ śrī-maṅgala-prema-kīrtyai namaḥ",
    devanagari: "ॐ श्रीमङ्गलप्रेमकीर्त्यै नमः",
    meaning: "Salutations to the One who has gained the reputation of being the most loving and benevolent in heralding auspiciousness.",
    category: "Auspiciousness",
  },
  {
    number: 96,
    iast: "oṃ śrī-niśumbha-kṣidāyai namaḥ",
    devanagari: "ॐ श्रीनिशुम्भक्षिदायै नमः",
    meaning: "Salutations to the One who destroys all negativity and arrogance in us.",
    category: "Transformation",
  },
  {
    number: 97,
    iast: "oṃ śrī-śumbha-darpatu-vahāyai namaḥ",
    devanagari: "ॐ श्रीशुम्भदर्पत्वहायै नमः",
    meaning: "Salutations to the One who destroyed the arrogance of Śumbha — Her ability to destroy all negativity around us.",
    category: "Transformation",
  },
  {
    number: 98,
    iast: "oṃ śrī-ānanda-bījādi-svarūpāyai namaḥ",
    devanagari: "ॐ श्रीआनन्दबीजादिस्वरूपायै नमः",
    meaning: "Salutations to the One who sows seeds of happiness and bliss in sincere devotees.",
    category: "Joy",
  },
  {
    number: 99,
    iast: "oṃ śrī-mukti-svarūpāyai namaḥ",
    devanagari: "ॐ श्रीमुक्तिस्वरूपायै नमः",
    meaning: "Salutations to the One who grants self-realization and ultimately liberates by granting Mokṣa.",
    category: "Liberation",
  },
  {
    number: 100,
    iast: "oṃ śrī-caṇḍa-muṇḍā-padāyai namaḥ",
    devanagari: "ॐ श्रीचण्डमुण्डापदायै नमः",
    meaning: "Salutations to the One who is Śrī Durgā (Cāmuṇḍā) — who removes the negative qualities of cruelty, greed and arrogance to help us grow spiritually.",
    category: "Transformation",
  },
  {
    number: 101,
    iast: "oṃ śrī-mukhya-caṇḍāyai namaḥ",
    devanagari: "ॐ श्रीमुख्यचण्डायै नमः",
    meaning: "Salutations to the One who surges in to destroy all forms of cruelty and bestow kindness — removing ailments of the heart cakra.",
    category: "Transformation",
  },
  {
    number: 102,
    iast: "oṃ śrī-pracaṇḍā-apracaṇḍāyai namaḥ",
    devanagari: "ॐ श्रीप्रचण्डाऽप्रचण्डायै नमः",
    meaning: "Salutations to the One who transforms the excessively violent and cruel to the most benevolent through Her grace.",
    category: "Transformation",
  },
  {
    number: 103,
    iast: "oṃ śrī-mahā-caṇḍa-vegāyai namaḥ",
    devanagari: "ॐ श्रीमहाचण्डवेगायै नमः",
    meaning: "Salutations to the One who rapidly destroys negativity and bestows peace and prosperity to devotees.",
    category: "Protection",
  },
  {
    number: 104,
    iast: "oṃ śrī-calac-cāmarāyai namaḥ",
    devanagari: "ॐ श्रीचलच्चामरायै नमः",
    meaning: "Salutations to the One who is fanned by a chowrie whisk — signifying removal of ignorance and all mental afflictions.",
    category: "Ritual",
  },
  {
    number: 105,
    iast: "oṃ śrī-cāmarā-candra-kīrtyai namaḥ",
    devanagari: "ॐ श्रीचामराचन्द्रकीर्त्यै नमः",
    meaning: "Salutations to the One worshipped by waving a fly-whisk around Her head adorned with a moon — signifying cleansing of ignorance and clearing our aura.",
    category: "Ritual",
  },
  {
    number: 106,
    iast: "oṃ śrī-sucāmikarāyai namaḥ",
    devanagari: "ॐ श्रीसुचामिकरायै नमः",
    meaning: "Salutations to the One who is boundless in Her virtuous actions and benevolence to sincere devotees.",
    category: "Grace",
  },
  {
    number: 107,
    iast: "oṃ śrī-citra-bhūṣojjvala-aṅgyai namaḥ",
    devanagari: "ॐ श्रीचित्रभूषोज्ज्वलाङ्ग्यै नमः",
    meaning: "Salutations to the One who is most beautifully adorned with various ornaments — dazzling and stunning in boundless beauty and splendor.",
    category: "Beauty",
  },
  {
    number: 108,
    iast: "oṃ śrī-su-saṅgīta-gītāyai namaḥ",
    devanagari: "ॐ श्रीसुसङ्गीतगीतायै नमः",
    meaning: "Salutations to the One who sings melodiously and is the very source of sound in all creation. She is Śabda Brahman — the manifestation of Superconsciousness as Sound and Syllable. She is the compendium of all knowledge, music and sound.",
    category: "Music & Speech",
  },
];

export const nameCategories = [
  "All",
  "Essence",
  "Wisdom",
  "Power",
  "Liberation",
  "Kundalini",
  "Music & Speech",
  "Nature",
  "Abundance",
  "Love",
  "Light",
  "Beauty",
  "Protection",
  "Transformation",
  "Union",
  "Consciousness",
  "Joy",
  "Victory",
  "Mother",
  "Tantra",
  "Karma",
  "Cosmic",
  "Meditation",
  "Realization",
  "Ritual",
  "Auspiciousness",
  "Sovereignty",
  "Glory",
  "Listening",
] as const;
